# Generated by Django 5.2.6 on 2025-11-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cita_estado_pago_pagocita'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinesiologo',
            name='precio_consulta',
            field=models.DecimalField(decimal_places=0, default=25000, help_text='Precio de la consulta en pesos chilenos', max_digits=10),
        ),
    ]
