# Generated by Django 5.2.6 on 2025-11-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_kinesiologo_precio_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='kinesiologo',
            name='atiende_consulta',
            field=models.BooleanField(default=True, help_text='Atiende en consulta/box propio'),
        ),
        migrations.AddField(
            model_name='kinesiologo',
            name='atiende_domicilio',
            field=models.BooleanField(default=False, help_text='Realiza atención a domicilio'),
        ),
        migrations.AddField(
            model_name='kinesiologo',
            name='atiende_online',
            field=models.BooleanField(default=False, help_text='Realiza atención online/telemedicina'),
        ),
        migrations.AddField(
            model_name='kinesiologo',
            name='comuna',
            field=models.CharField(blank=True, help_text='Comuna donde atiende', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kinesiologo',
            name='direccion_consulta',
            field=models.CharField(blank=True, help_text='Dirección de la consulta o box', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kinesiologo',
            name='region',
            field=models.CharField(blank=True, help_text='Región donde atiende', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='kinesiologo',
            index=models.Index(fields=['precio_consulta'], name='core_kinesi_precio__ba9b57_idx'),
        ),
        migrations.AddIndex(
            model_name='kinesiologo',
            index=models.Index(fields=['comuna'], name='core_kinesi_comuna_e102b7_idx'),
        ),
        migrations.AddIndex(
            model_name='kinesiologo',
            index=models.Index(fields=['especialidad'], name='core_kinesi_especia_46836f_idx'),
        ),
        migrations.AddIndex(
            model_name='kinesiologo',
            index=models.Index(fields=['estado_verificacion'], name='core_kinesi_estado__2a13c2_idx'),
        ),
    ]
