# Generated by Django 5.2.6 on 2025-11-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_kinesiologo_atiende_consulta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kinesiologo',
            name='atiende_online',
        ),
    ]
