# Generated by Django 5.2.6 on 2025-11-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_atiende_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='reseña',
            name='calificacion',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='Calificación de 1 a 5 estrellas'),
        ),
    ]
